io.go

ParseGbk now parses location to JSON.
I'd still consider this part of code unstable. To make it more stable I'd need a genbank file with 5' and 3' partial locations. I'd also need to rework the location extraction regex to be more bullet proof.

ParseGbk now parses location to JSON.

---

docs/library-hashing.md
docs/library-io.md
hash.go
hash_test.go
io.go
io_test.go
poly/commands.go
poly/commands_test.go
sequence.go
sequence_test.go
transformations.go
transformations_test.go

Refactoring IO as discussed in issue #51.

Refactor io

---

poly/commands.go
poly/commands_test.go
transformations.go

#63 has what might be some unsavable code but tests pass for the biggest test which is hashflags. I checked out a new branch and am committing what passes.

Hash flag test

---

poly/commands.go
poly/commands_test.go
transformations.go

I've increased test coverage in commands.go. There will likely need to be a refactor. So many unique conditionals that need to be consolidated and matrix tested. Merging for now.

increase test coverage

---

data/puc19static.json
poly/commands.go
poly/commands_test.go
poly/main.go

I've refactored commands. Test coverage is now in high 90's for command related code. There's still a few more things that need to be done but can be done later. I've removed a bunch of options in the hash command because they were hard to test and support.

Refactor commands

---

README.md

Updating the copyright date on the readme to 2021.

Updating the copyright date on the readme.

---

transformations.go

Remove mention of docs site on transformations

---

random/random.go
random/random_test.go

I wrote this as a test for github co-pilot and figured I may as well just merge it.

added random.DNASequence function.

---

synthesis/synthesis.go

This change actually make synonymous codons being selected correctly by highest weight. As you could see we actually now have a lot of errors in other functions, but I take a look in some of them and they're actually incorrectly.
One example is `synthesis_test.go:103: Failed to fix GGGCCC -> GGTCCC`
This test uses the pichaTable.json codon table, and you could see that actually the GGG synonymous codon with highest weight that fullfils a decrease in GC content is actually GGA and not GGT.
`
{
"letter": "G",
"codons": [
{
"triplet": "GGT",
"weight": 42959
},
{
"triplet": "GGC",
"weight": 18853
},
{
"triplet": "GGA",
"weight": 43541
},
{
"triplet": "GGG",
"weight": 14618
}
]
}
`

Synthesis fix for correctly choose the highest synonymous codon #192

---

synthesis/synthesis.go

Fixes #199 
I added a transaction during the building part of the synthesis fixer. Using the benchmark on my computer, it increased speed from 1106721399 ns/op to 30945020 ns/op.
This equates to approximate ~35x speedup with extremely limited addition of code.

Added transaction

---

cmd/poly/main.go

overide -> override

---

.gitignore

added linux/osx/windows and vim/vscode/emacs/jetbrains

update .gitignore with new OS and EDITOR ignore templates

---

primers/primers.go
primers/primers_test.go

Reverts TimothyStiles/poly#214

Revert "Add GcContent function to barcodes"

---

primers/primers.go
primers/primers_test.go

Tim borked the thing I unborked the thing (bork Etymology 2 https://en.wiktionary.org/wiki/bork)

Gc content fix tim bork

---

io/io.go
synthesis/synthesis.go

fill in missing package strings.

---

.gitpod.yml

gitpod tutorial commands on startup.

---

README.md

New go modules requires version.

Fix README installation method

---

io/genbank/genbank.go

Remove redundant Linear struct member

---

synthesis/codon/example_test.go

Fixes #306 
Makes optimization example clearer

updated example optimize

---

synthesis/codon/codon.go
synthesis/codon/codon_test.go

This fixes a simple bug where amino acids aren't found by optimize if they aren't capitalized.

bug fix amino acid capitalization

---

io/fastq/fastq.go

Updated fastq to solve #325 and #323

---

align/align.go

I was a little confused about which alignment algorithm to use, so I did some research and summarized it in the comments here.

add bit comparing alignment techniques

---

.github/workflows/blocking_issues.yml

https://github.com/marketplace/actions/blocking-issues
Part of #346 .

Add "blocked by" relationships between issues/PRs

---

.github/workflows/stale.yml

Mark issues and PRs as stale after 2 months

---

CHANGELOG.md

Add `CHANGELOG.md`. Populate it with current unreleased changes since v0.26.0.
Fixes #369 .
This is a devops/documentation change, so no.
*All of these must be satisfied before this PR is considered ready for merging. Mergeable PRs will be prioritized for review.*

Add `CHANGELOG.md` with current unreleased changes.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

While I'm here, drop the mention of the beginner issue tag as we currently don't have it.
Fixes #345 .

Add the poly Google group email as a method of contact.

---

.github/workflows/help_wanted_notify.yml

Fix help wanted discord webhook

---

.github/workflows/release.yml
justfile

Fix typo that caused coverage badge action to not work

Fix coverage action

---

.github/workflows/lint.yml

Pass in `-c .golangci.yml` as an explicit parameter to `golangci-lint-action` to ensure local and remote linting is the same.
Ensures same behavior on local and remote lint runs.
No.

Ensure lint workflow uses .golangci.yml

---

.gitattributes

Vendors justfiles show they do not show up in language stats.

vendored justfiles in .gitattributes.
