bebop/poly

commands_test.go, hash.go, hash_test.go
As pointed out in issue #23 there should be a forced default for uppercasing sequences before hashing them.
There should be a default over ride to allow lowercase or no case enforcing but that can come in a later pull request.
=> quick patch for hash consistency.

hash.go, hash_test.go, io.go, poly/commands.go, poly/commands_test.go
I've refactored hash.go to be more streamlined. There are also some breaking changes to general usage.
=> refactored hash.go. Now exposes only two hashing methods.

data/flatGbk_test.seq, data/multiGbk_test.seq, io.go, io_test.go
Closes #75 
Adds functionality to parse and read multi-genbank files and genbank flat files (like the ones exported from the Genbank FTP server). 
I did NOT add Build or Write functions for these 2 - I wasn't quite sure how they'd fit into the rest of the Poly ecosystem, but these seemed easy enough to add, and give functionality necessary for testing out how Poly operates when given ALL OF GENBANK.
=> Adds func for reading multi and flat genbank files

data/phix174.gb, transformations.go, transformations_test.go
Adds a single function called `CompromiseCodonTable` to transformations.go
This function takes 2 codon tables and compromises them together. Very useful for creating compromise tables between E.coli and B.subtilis for example (I would like to use this for some genes I am optimizing for formate bioutilization).
=> Added CompromiseCodonTable to Poly

hash.go, hash_test.go, io.go
This PR adds the Seqhash function and SequenceSeqhash method to Sequence structs. 
Briefly, the algorithm uniquely hashes DNA, RNA, and Protein sequences. It checks for properly formed sequences (no X nucleotide or amino acids) and has full test coverage with written examples.
Seqhash's primary use case is navigation between different databases. In particular, they can be used to do a full comparison of Genbank <-> Uniprot to get EC numbers for any protein.
=> Seqhash v1

hash.go, poly/main.go
Code climate was complaining about generic exports outside of main.go for the command line tool. So I moved them.
=> fixed generic import paths for hash functions.

poly/commands.go, poly/commands_test.go, poly/main.go
Thinking about this: `// TODO write basic check to see if input flag or all paths have accepted file`
Noticed, the weird logic of `fileParser` is probably the reason behind this TODO:
`poly convert -i gbk file.gff` will parse correctly, but `poly convert -i gff file.gbk` will error. (assuming the file extensions are correct).
This PR proposes that the `-i` should only be used when the file is being piped: `cat data/bsub.gbk | poly c -i gbk -o json > test.json`
delete `fileParse`, replace calls to it with `parseExt`.
This has the added benefit of increasing test coverage, since `fileParse` is not in any tests, while `parseExt` in only in tests. 
how should passing `-i` be handled when the input source is not a pipe? 
Currently it is ignored, but probably should throw an error. Unsure how …
=> Delete file parser

data/pichia_chr1_head.gb, io.go, io_test.go
Closes #124 
I fixed the error by allowing multiline genbank feature locations. I don't know what the heck `join(<459260..459456,459556..459637,459685..459739,459810..>460126)` means... but the parsing works, at least.
=> Fixed pichia error by adding multiline genbank feature locations

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .vscode/extensions.json, CONTRIBUTING.md
Added vscode dev container settings. Should install the go package a couple of other vscode plugins. Currently, the dev container image uses a Ubuntu Focal Container and installs golang using the latest apt package `golang`.
This dev container also installs the following plugins:
1. `golang.go`
2. `ms-vsliveshare.vsliveshare-pack`
3. `redhat.vscode-yaml`
4. `yzhang.markdown-all-in-one`
5. `premparihar.gotestexplorer`
6. `github.vscode-pull-request-github`
7. `streetsidesoftware.code-spell-checker`
8. `eamodio.gitlens`
=> Enables Dev Container #117

cmd/poly/commands_test.go, io/genbank/genbank.go, io/genbank/genbank_test.go, io/gff/gff.go, poly.go
This adds simple concurrent parsing for genbank files. I added two functions:
1. ParseConcurrent: Parses a mutli-genbank file into a channel
2. ParseFlatConcurrent: Parses a flat-genbank file into a channel
I also added an MD5 hash into the Sequence struct. This will be used in allbase to see if genbank files should be updated.
=> Added concurrent parsing feature for genbank files

data/benchling.gb, io/genbank/genbank.go, io/genbank/genbank_test.go
I have found that GenBank files exported from Benchling actually have 29 spaces between the beginning of the line and the first slash that it's used to identify a qualifier. Without this correction, the 17 features inside the `benchling.gb` file will only return the first one. I created a test in the final part of the `genbank_test.go` for this.
=> Fix for genbank files exported from benchling that have a different index for slash in qualifiers

synthesis/codon/codon.go, synthesis/codon/codon_test.go
This PR addresses issue #201 by updating `codon.Optimize` to gracefully handle protein sequences where at least one amino acid is missing from the codon table. A new custom error was added to enable the caller to find the offending amino acid.
Alternatively, `Optimize` could validate the protein sequence before building the codon chooser map. That would require a slightly bigger change to this function and would slow down the execution for valid inputs. On the upside, it could be beneficial to fail faster and to return the full set of invalid amino acids (as opposed to only the first one). Please let me know if that would be preferable.
=> Handle invalid amino acids in codon optimization

primers/primers.go, primers/primers_test.go
This PR adds `CreateBarcodesGcRange` into `primers`. It gives users a more intuitive interface for generating barcodes that are within a given GC content, which is important when designing PCR primers and the like for barcoding sequences.
100% test coverage maintained.
=> Add GcContent function to barcodes

README.md
Quick fix in Readme from "go install" to "go get"
=> Fixing Readme install instruction

transform/variants/variants.go, transform/variants/variants_test.go
In this PR, I'm making a few small tweaks to the variants package, and I've increased test coverage to 100%
- Fix a typo for iteratitive -> iterative
- Rename the test package from variants_test to variants to permit testing of private function
- Increase test coverage to 100%
- Use the assert package to fail tests, as this is more succinct than if statements
If the changes here are acceptable, I can move on to increasing coverage in other packages.
=> Increase coverage for the variants package

.github/workflows/coverage.yml, README.md
The old coverage badge was with code cov and completely unreliable. This new one is entirely through github actions and uses github gists to store information for badge generation. It should be far more stable and accurate.
=> created non-third party coverage badge.

.github/workflows/golangci-lint.yml, .github/workflows/notify.yml, io/fasta/fasta.go, io/genbank/example_test.go, io/genbank/genbank.go, io/genbank/genbank_test.go, io/gff/example_test.go, io/gff/gff.go, io/gff/gff_test.go, io/polyjson/example_test.go, io/polyjson/polyjson.go, io/rebase/rebase.go, seqhash/example_test.go, seqhash/seqhash.go, synthesis/codon/codon.go, synthesis/codon/example_test.go
Replaced the sequenceType argument with an Enum. 
Currently using the direct const type enum. 
Addressing - #264
=> Replaced the Seqhash sequencetype with Struct type argument instead of a plain string..

.github/workflows/notify.yml, .github/workflows/tweet.yml, synthesis/fix/synthesis.go
```console
$ go version
go version go1.19.1 linux/amd64
$ go test -run=ExampleCds .
ok  	github.com/TimothyStiles/poly/synthesis/fix	0.008s
```
Fixes https://github.com/golang/go/issues/55009
=> fix: Use SliceStable to sort potential changes

.gitpod.yml
Without this, VS Code prompts to install `gopls`, `dlv`, etc. before setting a breakpoint + debugging a tutorial works.
I'm not sure if there's a more elegant way to run `Go: Install/Update Tools` (https://github.com/golang/vscode-go/wiki/tools) in the Command Palette instead.
Also simplified the check for `$tutorial`, as otherwise this line causes a syntax error when the variable isn't set at all.
=> Install Go Analysis Tools in Gitpod workspace

io/genbank/genbank.go
This PR precompiles most of the regular expressions except for `genBankMoleculeTypes` and `genbankDivisions`.
Same approach as #273.
Results in ~10% less allocations and ~10% speed improvement.
`benchcmp` output:
```
% benchcmp bench_main.txt bench_new.txt 
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                old ns/op     new ns/op     delta
BenchmarkRead-8          51142         44201         -13.57%
BenchmarkRead1-8         50456         45411         -10.00%
BenchmarkRead10-8        50317         44153         -12.25%
BenchmarkRead100-8       50074         44064         -12.00%
BenchmarkRead1000-8      49935         44106         -11.67%
BenchmarkRead10000-8     50119         44117         -11.98%
benchmark …
```
=> Precompile most of the regular expressions

io/genbank/genbank.go, io/gff/gff.go, synthesis/codon/codon.go
Removes a few unnecessary conversions reported by `unconvert`:
```
% golangci-lint run -E unconvert ./...
io/gff/gff.go:253:26: unnecessary conversion (unconvert)
featureStrand := string(feature.Strand)
^
io/genbank/genbank.go:748:30: unnecessary conversion (unconvert)
baseSequenceLength := string(basePairRegex.FindString(locusString))
^
synthesis/codon/codon.go:426:27: unnecessary conversion (unconvert)
_ = json.Unmarshal([]byte(file), &codonTable)
```
=> Remove unnecessary conversions

clone/clone.go
I think that this might be useful and perform better if you're calling `getBaseRestrictionEnzymes` multiple times in the same function. Before this change, `getBaseRestrictionEnzymes` would compile the same regular expressions over and over.
=> Move enzymeMap to package level, compile regular expressions only once

tutorials/000_introduction_test.go
There was a missing word in the first tutorial.
=> Typo in tutorial

transform/examples_test.go, transform/transform.go, transform/transform_test.go
Lot of noise in this PR, sorry about that. What matters is that
* I'm using a 256byte table for complement calculation instead of map
* I'm avoiding heap allocations where possible by using a byte slice and unsafe conversion.
```go
// ReverseComplement takes the reverse complement of a sequence.
// ReverseComplement expects ASCII input.
func ReverseComplement(sequence string) string {
n := len(sequence)
newSeq := make([]byte, n)
for i := 0; i < n; i++ {
newSeq[i] = complementTable[sequence[n-i-1]]
}
// This is how strings.Builder works with the String() method. If Mr. Go says it's safe...
return *(*string)(unsafe.Pointer(&newSeq))
}
```
=> transform: performance like it matters

io/rebase/rebase.go, io/rebase/rebase_test.go
First contribution to the repo, an attempt to fix #278
=> Support multiple references separated by newline in rebase file

align/align.go, clone/clone.go, io/rebase/rebase.go, random/random.go, seqhash/seqhash.go
=> fix comment typos

synthesis/fragment/fragment.go, synthesis/fragment/fragment_test.go
NewOverhangs didn't use to check if the reverse complement of the next overhang already existed. Now it checks. Yay.
=> Add checks for reverse sequence in fragment

io/slow5/slow5.go
Stupid simple addition. parser.line wasn't iterating in slow5 parser, so error messages would be a bit non-nonsensical. Fixed this with 1 line addition.
Ready for merge.
=> add parser.line++ so error messages make sense

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Part of #346 .
Cleaned up the issue templates to make them look nicer and be more applicable to our needs.
The more controversial part is disabling blank issues - I know @Koeng101 had said that he and Tim would likely not use issue templates, but I think that this will provide a greater incentive for people to fill out issues with more complete information that will help us triage and provide a fix. There's still always the option of deleting all the text in the template, anyway :wink:
=> Update issue templates and disable blank issues.

.github/pull_request_template.md
Add a PR template. This PR itself uses this template to give everyone an idea of what the template is like.
A PR template will make it easier to track what changes are made and ensure new changes satisfy all documentation and testing requirements. Part of #346 .
This is a devops/documentation change, so no.
*All of these must be satisfied before this PR is considered ready for merging. Mergeable PRs will be prioritized for review.*
=> Add a pull request template.

primers/pcr/pcr.go, primers/pcr/pcr_test.go
In `generatePcrFragments()`, there was a loop that was erroneously iterating over the indices of `forwardPrimerIndxs` rather than the values of the slice itself.
Fixes #279 .
No.
=> Fix PCR bug (issue #279).

.github/workflows/take.yml
Adds a GitHub action that allows non-contributors to self-assign issues when they include ".take" in an issue comment.
Allows for non-contributors to indicate they are working on an issue. Part of #346 .
No.
=> Allow non-contributors to take an issue with .take

.github/workflows/take.yml
Fix a YAML syntax error in the take.yml GitHub Action, changing `//` to `#` to properly mark a comment.
GitHub Action is currently broken due to this syntax error.
No.
=> Fix YAML syntax error in take.yml

data/sample.gbk, io/genbank/genbank.go
I've patched the genbank parser and builder to handle the BASE COUNT line.
Not handling this breaks the parser and cases it to throw an error.
NO.
=> patched genbank parser and builder to handle BASE COUNT.

mash/mash.go, mash/mash_test.go
- Optimizes the mash similarity function: removed `sort.Search` usage, merged the early exit conditions and rewrote the sketch traversing logic.
- Adds simple `mash.Distance` benchmark.
- General optimization:
```
% benchcmp old.txt new.txt 
benchmark           old ns/op     new ns/op     delta
BenchmarkMash-8     118           9.71          -91.75%
BenchmarkMash-8     113           9.72          -91.43%
BenchmarkMash-8     113           9.71          -91.43%
benchmark           old allocs     new allocs     delta
BenchmarkMash-8     0              0              +0.00%
BenchmarkMash-8     0              0              +0.00%
BenchmarkMash-8     0              0              +0.00%
benchmark           old bytes     new bytes     delta
BenchmarkMash-8     0             0             +0.00% …
```
=> mash: optimize mash similarity function, add benchmark

CHANGELOG.md, clone/clone.go, clone/clone_test.go
fixed bug that produced wrong overhangs in linear, non-directional, single cut reactions.
There was a bug in CutWithEnzyme where in the case of linear, non-directional, single cut reactions, it would assume that the overhangs were produced by a forward facing cut site and return a sequence downstream. In the case of the cut being a reverse cut site it would return the wrong overhangs. This was fixed with a simple if-else
There are no breaking changes.
=> fixed bug that produced wrong overhang in linear, non-directional, single cut reactions.

.goreleaser.yml
Updating parameters for Go Releaser workflow.
1. changed owner from TimothyStiles to bebop
2. change draft from true to false. Will now auto-publish release
3. changed pre-release to true
4. name template has been truncated. Had been doing this manually on each release anyways.
General maintenance.
=> changed parameters in .goreleaser.yml

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test.yml, go.mod, io/slow5/slow5_test.go, random/random.go, synthesis/codon/codon.go
Bumps Golang version to latest stable one:  [1.21.4](https://go.dev/dl/)
Also ran `go mod tidy`.
Just keeping it up to date and I also think there can be many benefits, for example I explored the new `slices` package which is recommended and more performant than `sort` methods in a few scenarios, etc.
No - tests are fine too
=> Bump Golang version

tutorials/000_introduction_test.go, tutorials/001_input_output_test.go, tutorials/README.md
I've removed any mention of GitPod from the tutorials section and fixed some typos.
GitPod broke a while back and it's a little too much to maintain for what it gives us. May find an alternative in the future but for now deleting
No
=> Update tutorials no gitpod

.github/pull_request_template.md
Lines providing info on how to fill out the pull request are now commented out.
Will make things look neater.
No
=> Comment out info lines of pull request template

CONTRIBUTING.md
Document the workflow changes discussed in #346 
Sets up a standard for issue management, which will be important as we get more of em.
No
=> Add issue management info to CONTRIBUTING

synthesis/codon/codon.go, synthesis/codon/codon_test.go, synthesis/codon/example_test.go
The hardcoded codon table objects are no longer generated at buildtime (which makes them global variables prone to being changed by an unexpected process) but initialised as part of their constructor; `NewTranslationTable`. This ensures that the package examples and tests run in proper isolation (and that no consumer gets surprised when they modify a table's weights and find that they've also updated a separate, unrelated table).
This PR also makes the codonTable.Copy() function [less naive](https://stackoverflow.com/questions/56355212/deep-copying-data-structures-in-golang), which was [originally created](https://github.com/bebop/poly/pull/350#discussion_r1333319177) to avoid this "global variable" problem but was too naive. Ideally we would not need to make deep copies; but it is used …
=> Fixing updateweights example

fold/fold_test.go, fold/seqfold_test.go
added some more test coverage to fold subpackage.
To increase code coverage of fold package.
No
=> added some more test coverage to fold subpackage.

CHANGELOG.md, search/bwt/bwt.go, search/search.go
Two packages are making doc strings.
For better documentation.
No
=> added package level doc strings.

.devcontainer/devcontainer.json
Updating the devcontainer to use go 1.23 and debian 12 `bookworm`.
Originally wanted to use a smaller dev container for faster builds but the official Go devcontainer images don't support alpine?
No. It builds and all tests pass within the build.
=> updated devcontainer image.
